version: '3'

services:
  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION=mongodb://db:27017/profile
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mongo:5.0.8
    ports:
      - "27017:27017"

